### ISSUE TITLE
Got request timeout from nodejs api after a long period of inactivity

### ISSUE THREAD

**Issue by tgabi333** [Kurento/bugtracker#1]
I have connected to KMS using kurento-client through secure websocket. It worked as well. I left my node server running with  this open connection for a night, - no communication happened and now in the morning i've tried to register a new pipeline.

Using: KMS 6.1.1  on a distant network

```
{ [Error: Request has timed out]
  request: '{"jsonrpc":"2.0","method":"create","params":{"type":"MediaPipeline","sessionId":"1af516ae-068d-43ff-ac81-1d00ad3e083c"},"id":23}',
  retry: [Function: retry] }
Error: Request has timed out
    at /workspace/videochat/node_modules/kurento-client/lib/KurentoClient.js:332:24
    at /workspace/videochat/node_modules/kurento-client/lib/KurentoClient.js:504:16
    at callback2 (/workspace/videochat/node_modules/promisecallback/index.js:27:25)
    at lib$es6$promise$$internal$$tryCatch (/workspace/videochat/node_modules/es6-promise/dist/es6-promise.js:331:16)
    at lib$es6$promise$$internal$$invokeCallback (/workspace/videochat/node_modules/es6-promise/dist/es6-promise.js:343:17)
    at /workspace/videochat/node_modules/es6-promise/dist/es6-promise.js:891:13
    at lib$es6$promise$asap$$flush (/workspace/videochat/node_modules/es6-promise/dist/es6-promise.js:125:9)
    at process._tickDomainCallback (node.js:381:11)
```

Looking at the network stats:
```
tcp        0      0 10.0.2.15:49978         x.x.x.x:8433     ESTABLISHED
```

And found these lines in the server log:
```
2015-10-14 10:32:58,718016 2390 [0x00007f6550ff9700]    info KurentoWebSocketTransport WebSocketTransport.cpp:257 keepAliveSessions()  Keep alive 1af516ae-068d-43ff-ac81-1d00ad3e083c
```

Could you please help me how to keep open the connection?

**Comment by jcaden** [comment]
Can to attach kms log please?

**Comment by tgabi333** [comment]
https://clbin.com/VLeGH
and
https://clbin.com/i2jVy

Thank you

**Comment by jcaden** [comment]
This request didn't arrived to the server. There should be a problem with the reconnection of the websocket.

**Comment by igracia** [comment]
It seem like we have a bug in kurento-jsonrpc-client. We'll have a look at that!

**Comment by igracia** [comment]
@rbenitez  Could you triage this, please? It seems like an issue in the KurentoClient in JavaScript. We should be reconnecting.

**Comment by tgabi333** [comment]
same happened today :(

**Comment by jcaden** [comment]
I guess it will be happening until reconnection is fixed :smile:

**Comment by tgabi333** [comment]
How can i help, in which repo?

**Comment by igracia** [comment]
We are debugging this. I'll get back to you as soon as we have solid info, but basically once the connection is lost, we are not reconnecting if needed. This happens after a certain idle time. There are workarounds and things that could be done about it, but we have a library that should be reconnecting. It looks like it's not working as it should.

**Comment by sainttail** [comment]
This still happen with kurento-client-js 6.2, somehow the connection die and reconnect not working so right now I have to capture the request timeout error and call client._re._connection.end() to force reconnection again.

**Comment by igracia** [comment]
@rbenitez Did you have a chance to take a look at this?

**Comment by rbenitez** [comment]
Hi @sainttail, please could you tell me which version are you using of kurento-client-js?

Thanks

**Comment by sainttail** [comment]
@rbenitez I'm currently using kurento-client-js 6.2.0 which just release recently.

**Comment by rbenitez** [comment]
Ok, I will investigate what's the problem. I will tell you something as soon as possible.

Best

**Comment by igracia** [comment]
@rbenitez Do we have new info on this?

**Comment by efdi** [comment]
@rbenitez @igracia Is there any progress?
Or are there any good hacks to work around this issue?

**Comment by rbenitez** [comment]
We have implemented a ping/pong mechanism and we have reimplemented the reconnection way, please update kurento-client at master version. 

Best.

**Comment by dfernandezlop** [comment]
@rbenitez can we close the bug?

**Comment by rbenitez** [comment]
Yes.

Un saludo.

---------------------------------------------------------
Raúl Benítez Mejías
https://twitter.com/rbenitezm
----------------------------------------------------------

2016-03-11 11:01 GMT+01:00 David Fernández López <notifications@github.com>:

**Comment by dfernandezlop** [comment]
Ok, I'm closing the thread.

**Comment by abhikandoi** [comment]
Hey guys I am still facing this issue. I am using kurento-media-server version `6.6.2`:

Here is the version output:

```abhi@black:~/kandoi/src# kurento-media-server -v
Version: 6.6.2
Found modules:
	Module: 'core' version '6.6.3'
	Module: 'elements' version '6.6.3'
	Module: 'filters' version '6.6.2'
```

I get the Error: `Request has timed out`. A quick hack to fix this would also be appreciated.
@sainttail can you please share the fix that you mention in this thread?
