### ISSUE TITLE
Node v6 freeze with kurento-client-js

### ISSUE THREAD

**Issue by tgabi333** [Kurento/bugtracker#71]
MediaObject.create promise never returns and the CPU usage is 100%

The problem is somewhere here: `MediaObject.prototype.then`

Cannot reproduce with node v.0.12, v4 and v5, only v6 freezes.

Got it from profiler:

```
 [Summary]:
   ticks  total  nonlib   name
  17315   12.4%   13.6%  JavaScript
  103010   74.0%   80.9%  C++
   4980    3.6%    3.9%  GC
  11893    8.5%          Shared libraries
   6944    5.0%          Unaccounted
```

and:

```
 [Bottom up (heavy) profile]:
  Note: percentage shows a share of a particular caller in the total
  amount of its parent calls.
  Callers occupying less than 2.0% are not shown.

   ticks parent  name
  12260    8.8%  v8::internal::LookupIterator::Next()
   3523   28.7%    v8::internal::Runtime_KeyedGetProperty(int, v8::internal::Object**, v8::internal::Isolate*)
   3518   99.9%      LazyCompile: *disguise /workspace/videochat/node_modules/kurento-client/lib/disguise.js:22:18
   3518  100.0%        LazyCompile: *MediaObject.then /workspace/videochat/node_modules/kurento-client-core/lib/abstracts/MediaObject.js:674:38
   3518  100.0%          LazyCompile: <anonymous> native promise.js:138:27
   3518  100.0%            Stub: CallApiAccessorStub {3}
   3366   27.5%    v8::internal::Runtime_ForInFilter(int, v8::internal::Object**, v8::internal::Isolate*)
   3366  100.0%      LazyCompile: *disguise /workspace/videochat/node_modules/kurento-client/lib/disguise.js:22:18
   3366  100.0%        LazyCompile: *MediaObject.then /workspace/videochat/node_modules/kurento-client-core/lib/abstracts/MediaObject.js:674:38
   3366  100.0%          LazyCompile: <anonymous> native promise.js:138:27
   3366  100.0%            Stub: CallApiAccessorStub {3}
   2723   22.2%    /usr/bin/nodejs
   2705   99.3%      LazyCompile: *disguise /workspace/videochat/node_modules/kurento-client/lib/disguise.js:22:18
   2705  100.0%        LazyCompile: *MediaObject.then /workspace/videochat/node_modules/kurento-client-core/lib/abstracts/MediaObject.js:674:38
   2705  100.0%          LazyCompile: <anonymous> native promise.js:138:27
   2705  100.0%            Stub: CallApiAccessorStub {3}
   2429   19.8%    v8::internal::Runtime_ObjectDefineProperty(int, v8::internal::Object**, v8::internal::Isolate*)
   2429  100.0%      LazyCompile: *defineProperty native v8natives.js:580:30
   2429  100.0%        LazyCompile: *disguise /workspace/videochat/node_modules/kurento-client/lib/disguise.js:22:18
   2429  100.0%          LazyCompile: *MediaObject.then /workspace/videochat/node_modules/kurento-client-core/lib/abstracts/MediaObject.js:674:38
   2429  100.0%            LazyCompile: <anonymous> native promise.js:138:27

```

**Comment by tgabi333** [comment]
seems related to this: https://github.com/stefanpenner/es6-promise/issues/190

**Comment by igracia** [comment]
Thanks for the feedback!

**Comment by tgabi333** [comment]
Mixing kurento's `es6-promise` and native `Promise` could cause this behavior.

We have a code like this:
```
addInstance: function (wsUrl, options) {
        logger.info('Adding new mediaserver at: ' + wsUrl);
        return new Promise(function (resolve, reject) {
            kurento.getSingleton(wsUrl, options, function (err, client) {
                if (err) {
                    logger.error('New mediaserver registration failed at ' + wsUrl, err);
                    reject.call(this, arguments);
                    return;
                }

                logger.info('New mediaserver at: ' + wsUrl);
                resolve(client);
            });
        });
    }
```
The freeze happens if i call native `promise.all` with the results above:
```
Promise.all(promises).then(...)
```

**Comment by tgabi333** [comment]
@igracia would mind if i create a pull requests to use the native Promise implementation if available and use only use es6-promise otherwise?

**Comment by igracia** [comment]
If you don't mind waiting, we'll implement that next week. We've had some issues recently with our internal Gerrit, and wouldn't want that to be lost.

@rbenitez Can you have a look at this? It should be easy peasy.

**Comment by tgabi333** [comment]
@igracia, @rbenitez Can i help you with it?

**Comment by rbenitez** [comment]
Hi @tgabi333, I'm sorry for late answer, how can I reproduce your problem?

Thanks

**Comment by tgabi333** [comment]
Yep:

Use the addInstance method above with native Promise implementation. Collect the results in an array and call `Promise.all(promises).then(...)`

You'll never get into `then`.

**Comment by rbenitez** [comment]
Please, @tgabi333 have you got any example more specific?

Thanks!

**Comment by tgabi333** [comment]
@rbenitez i will create a gist, just give me a few minutes, thank you.

**Comment by tgabi333** [comment]
This is the simplest example.
```
var kurento = require('kurento-client');

// With native promise it won't work under nodejs v6
//var Promise = require('es6-promise').Promise;

new Promise(function (resolve, reject) {
    kurento.getSingleton('TODO', function (err, client) {
        if (err) {
            reject.call(this, arguments);
            return;
        }

        resolve(client);
    });
}).then(function () {
    console.log('OK');
});
```

**Comment by rbenitez** [comment]
Thanks! I will try on this example and as soon as possible I will say something

**Comment by tgabi333** [comment]
The main problem is that we promisify callbacks with native Promise. But it won't resolve causing 100% cpu. 

I would suggest that use es6-promise only if there is no existing Promise implementation available.

**Comment by rbenitez** [comment]
HI @tgabi333, 

Sorry for the delay, I have done some tests with this issue.

We have updated the es6-promise version and add promise in the dependencies, in this [patch](https://github.com/Kurento/kurento-client-js/commit/4059d44d6aca09982607a0c479b9cedbf2f9dae7). And now, if you add in your code:

`var Promise = requiere('promise');`
before: 
 ```
new Promise(function (resolve, reject) {
    kurento.getSingleton('TODO', function (err, client) {
        if (err) {
            reject.call(this, arguments);
            return;
        }

        resolve(client);
    });
}).then(function () {
    console.log('OK');
});

```
The problem is solved.

**Comment by tgabi333** [comment]
Hi @rbenitez!

Thanks for your work, but it does not help in this case. It work well if i used your promise library (both es6-promise v2 and v3). 

But mixing promises with your non-native es6-promise implementation breaks node v6.

Native promises are more performant and widely available both in browsers and in nodejs (since 0.12)

I suggest to use the native implementation where you can and only use es6-promise when necessary. I've tested this and worked well in your codebase.

Change these lines
```
var Promise = require('es6-promise').Promise;
```

to:
```
if (typeof Promise !== 'function') {
    Promise = require('es6-promise').Promise;
}
```
(watch out for the missing var keyword)

**Comment by tgabi333** [comment]
@rbenitez, @igracia , Please reopen this this ticket, it is not solved. Force the clients to use the same promise library as yours is not a solution. I really appreciate your work, this software is amazing, could you please be more open to pull requests, i'd really like to contribute to your project to improve the quality of the software.

**Comment by rbenitez** [comment]
@tgabi333  sorry for the delay, we will do some tests about your proposal.

**Comment by igracia** [comment]
@tgabi333 We are back at this. Sorry for the delay. The thing is that we need to change the templates from the code generators too, and we were trying to avoid that. Since as @rbenitez has stated we can't reproduce this with our current tests, we are not sure if we'll be fixing it. In any case, we are back at this now.

**Comment by rbenitez** [comment]
Hi @tgabi333, 

Do you have some project (with mixing  non-native es6-promise and promise) where I can reproduce your problem? I don't get reproduce the problem.

Thanks

**Comment by tgabi333** [comment]
Sure, i will create a sample project.

**Comment by yehiyam** [comment]
You can find a sample project [here](https://github.com/yehiyam/kurento-node-problem), as I wrote in the forum [post](https://groups.google.com/d/msg/kurento/72giPvH8ppE/GVUYAzhXCAAJ)

**Comment by rbenitez** [comment]
Thanks @tgabi333 

I have seen the problem. We will try to fix it as soon as possible.

**Comment by tgabi333** [comment]
@rbenitez can i help you somehow?

**Comment by rbenitez** [comment]
Hi @tgabi333, we have a first solution. I hope that at the end of the week, we will can upload the solution.

Thanks

**Comment by rbenitez** [comment]
Hi @tgabi333, please in master branch there is a solution for this issue. I have been trying this code in you example and in another, and now it's working. During this afternoon I will do more tests in another project that we have.

Please, use kurentoClient as
"kurento-client": "Kurento/kurento-client-js" in your package.json
or like 
"kurento-client": "master" in your bower.json

I wait your feedback

Thank you.

**Comment by bits2work** [comment]
I am seeing similar problems in kurento client version 6.6.0. Callbacks work but even a wrapper function with promise never returns. 
Is there a new version available that includes a fix?

Here is my code snippet:

```
function getKurentoClient(uri, options, callback) {
  new KurentoClient(uri, options, (err, kms)=> {
    if (err) {
      callback("Can't create KMS instance", null);
    }
    else {
      callback("", kms);
    }
  });
}

// This prints "Got client instance .." but promise never returns.
function getClientAsPromise(uri, options) {
  return new Promise( (resolve, reject) => {
    getKurentoClient(uri, options, (err, kms) => {
      if (err) {
        console.error(err);
        reject(err);
      }
      else {
        console.info("Got client instance - as promise");
        resolve(kms);
      }
    });
  });
}

// This callback version works.
function getClientAsCallback(uri, options, callback) {
  getKurentoClient(uri, options, (err, kms) => {
    if (err) {
      console.error(err);
      callback(err, null);
    }
    else {
      console.info("Got client instance - as callback");
      callback("", kms);
    }
  });
}

```

**Comment by tgabi333** [comment]
Thank you! It works with node v7.

**Comment by tgabi333** [comment]
@rbenitez You can now safely remove `es6-promise` from package.json

**Comment by yehiyam** [comment]
Has the npm package been updated to reflect the fix?

**Comment by alex00888** [comment]
I have the same problem

**Comment by tgabi333** [comment]
It sadly seems that kurento development is dead as @Twilio appeared.

@alex00888 a workaround: use master in your package.json file: 
`"kurento-client": "https://github.com/Kurento/kurento-client-js#master"`

**Comment by subpardaemon** [comment]
is it really dead? i'm beginning to be afraid, seeing as how the open tickets just keep mounting here -- without answers to most.

**Comment by tgabi333** [comment]
There is a new project at top of kurento: https://github.com/OpenVidu 

But im afraid there will be a long time when it's will be usable
